version: '3.8'

services:
  mongodb:
    image: mongo:4.4.13
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_admin
      MONGO_INITDB_ROOT_PASSWORD: db_admin
      MONGO_INITDB_DATABASE: db_ware
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped